apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tf-operator
  template:
    metadata:
      labels:
        name: tf-operator
    spec:
      serviceAccountName: tf-operator
      containers:
        - name: tf-operator
          # Replace this with the built image name
          image: tf-operator:v0.0.1
          command:
          - tf-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tf-operator"
